# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the local app.py file into the container at /app
COPY app.py .

# Specify the command to run the application
CMD ["python", "app.py"]
