name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image
      run: docker build -t teodorabaluta/2-simpleapp:${{ github.sha }} -t teodorabaluta/2-simpleapp:latest .
    
    - name: Push Docker image
      run: docker push teodorabaluta/2-simpleapp:${{ github.sha }} && docker push teodorabaluta/2-simpleapp:latest
